from functionDefined import cap_cal
J = float(input('Enter % of cat J: '))
H = float(input('Enter % of cat H: '))
M = float(input('Enter % of cat M: '))
L = float(input('Enter % of cat L: '))
A = float(input('Enter % of class A: '))
B = float(input('Enter % of class B: '))
C = float(input('Enter % of class C: '))
D = float(input('Enter % of class D: '))
E = float(input('Enter % of class E: '))
ROT1 = float(input('Enter ROT of class A: '))
ROT2 = float(input('Enter ROT of class B: '))
ROT3 = float(input('Enter ROT of class C: '))
ROT4 = float(input('Enter ROT of class D: '))
ROT5 = float(input('Enter ROT of class E: '))
S = float(input('Enter the arrival separation minima: '))
w = float(input('Enter the OM-THR distance: '))
l = float(input('Final approach segment length: '))
RESULT = cap_cal(J, H, M, L, A, B, C, D, E, ROT1, ROT2, ROT3, ROT4, ROT5, S, w, l)
print(RESULT)